---

version: '3'

services:
  jenkins:
    image: symbolspace/jenkins-dotnet:latest
    container_name: jenkins
    hostname: jenkins
    restart: always
    #ports:
    #  - "8080:8080"
    #  - "50000:50000"
    networks:
      default:
        ipv4_address: 172.243.254.252
    user: root
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./../data/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

networks:
  default:
    external:
      name: web_hub_1
